In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("movies_metadata.csv")

C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\2203978780.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("movies_metadata.csv")

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.tail()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [5]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [6]:
df.shape

(45466, 24)

In [7]:
df.loc[5]

adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            60000000
genres                   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
homepage                                                               NaN
id                                                                     949
imdb_id                                                          tt0113277
original_language                                                       en
original_title                                                        Heat
overview                 Obsessive master thief, Neil McCauley leads a ...
popularity                                                       17.924927
poster_path                               /zMyfPUelumio3tiDKPffaUpsQTD.jpg
production_companies     [{'name': 'Regency Enterprises', 'id': 508}, {...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-12-15
revenue                                                        187436818.0
runtime                                                              170.0
spoken_languages         [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
status                                                            Released
tagline                                           A Los Angeles Crime Saga
title                                                                 Heat
video                                                                False
vote_average                                                           7.7
vote_count                                                          1886.0
Name: 5, dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [9]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
df.duplicated().sum()

13

In [11]:
df=df.drop_duplicates()

In [12]:
df.duplicated().sum()

0

In [13]:
df=df[['genres','overview','production_companies','title','original_language','popularity']]

In [14]:
df

,genres,overview,production_companies,title,original_language,popularity
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",Toy Story,en,21.946943
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Jumanji,en,17.015539
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Grumpier Old Men,en,11.7129
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Waiting to Exhale,en,3.859495
4,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Father of the Bride Part II,en,8.387519
...,...,...,...,...,...,...
45461,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman.,[],Subdue,fa,0.072051
45462,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,"[{'name': 'Sine Olivia', 'id': 19653}]",Century of Birthing,tl,0.178241
45463,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...","[{'name': 'American World Pictures', 'id': 6165}]",Betrayal,en,0.903007
45464,[],"In a small town live two brothers, one a minis...","[{'name': 'Yermoliev', 'id': 88753}]",Satan Triumphant,en,0.003503
45465,[],50 years after decriminalisation of homosexual...,[],Queerama,en,0.163015

In [15]:
df.isnull().sum()

genres                    0
overview                954
production_companies      3
title                     6
original_language        11
popularity                5
dtype: int64

In [16]:
df=df.dropna(subset=['title'])

In [17]:
df['overview']=df['overview'].fillna(' ')

C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\2502965232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview']=df['overview'].fillna(' ')

In [18]:
df.isnull().sum()

genres                   0
overview                 0
production_companies     0
title                    0
original_language       11
popularity               0
dtype: int64

In [19]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [20]:
import ast

In [21]:
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\287082524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [22]:
df['genres'][0]

'Animation Comedy Family'

In [23]:
df['production_companies'][0]

"[{'name': 'Pixar Animation Studios', 'id': 3}]"

In [24]:
df['production_companies']=df['production_companies'].apply(lambda x:" ".join(i['name'] for i in ast.literal_eval(x)))

C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\763779270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['production_companies']=df['production_companies'].apply(lambda x:" ".join(i['name'] for i in ast.literal_eval(x)))

In [25]:
df['production_companies'][0]

'Pixar Animation Studios'

In [26]:
df['original_language'].value_counts()

original_language
en    32260
fr     2437
it     1529
ja     1349
de     1079
      ...
ay        1
rw        1
cy        1
tg        1
si        1
Name: count, Length: 89, dtype: int64

In [27]:
df

,genres,overview,production_companies,title,original_language,popularity
0,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,Toy Story,en,21.946943
1,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,TriStar Pictures Teitler Film Interscope Commu...,Jumanji,en,17.015539
2,Romance Comedy,A family wedding reignites the ancient feud be...,Warner Bros. Lancaster Gate,Grumpier Old Men,en,11.7129
3,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Twentieth Century Fox Film Corporation,Waiting to Exhale,en,3.859495
4,Comedy,Just when George Banks has recovered from his ...,Sandollar Productions Touchstone Pictures,Father of the Bride Part II,en,8.387519
...,...,...,...,...,...,...
45461,Drama Family,Rising and falling between a man and woman.,,Subdue,fa,0.072051
45462,Drama,An artist struggles to finish his work while a...,Sine Olivia,Century of Birthing,tl,0.178241
45463,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",American World Pictures,Betrayal,en,0.903007
45464,,"In a small town live two brothers, one a minis...",Yermoliev,Satan Triumphant,en,0.003503
45465,,50 years after decriminalisation of homosexual...,,Queerama,en,0.163015

In [28]:
df['tag1']=df['genres']+" "+df['overview']
df['tag2']=df['production_companies']+" "+df['original_language']

C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\1077446646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag1']=df['genres']+" "+df['overview']
C:\Users\bhand\AppData\Local\Temp\ipykernel_26000\1077446646.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag2']=df['production_companies']+" "+df['original_language']

In [29]:
df['tag1'][0]

"Animation Comedy Family Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [30]:
df

,genres,overview,production_companies,title,original_language,popularity,tag1,tag2
0,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",Pixar Animation Studios,Toy Story,en,21.946943,"Animation Comedy Family Led by Woody, Andy's t...",Pixar Animation Studios en
1,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,TriStar Pictures Teitler Film Interscope Commu...,Jumanji,en,17.015539,Adventure Fantasy Family When siblings Judy an...,TriStar Pictures Teitler Film Interscope Commu...
2,Romance Comedy,A family wedding reignites the ancient feud be...,Warner Bros. Lancaster Gate,Grumpier Old Men,en,11.7129,Romance Comedy A family wedding reignites the ...,Warner Bros. Lancaster Gate en
3,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Twentieth Century Fox Film Corporation,Waiting to Exhale,en,3.859495,"Comedy Drama Romance Cheated on, mistreated an...",Twentieth Century Fox Film Corporation en
4,Comedy,Just when George Banks has recovered from his ...,Sandollar Productions Touchstone Pictures,Father of the Bride Part II,en,8.387519,Comedy Just when George Banks has recovered fr...,Sandollar Productions Touchstone Pictures en
...,...,...,...,...,...,...,...,...
45461,Drama Family,Rising and falling between a man and woman.,,Subdue,fa,0.072051,Drama Family Rising and falling between a man ...,fa
45462,Drama,An artist struggles to finish his work while a...,Sine Olivia,Century of Birthing,tl,0.178241,Drama An artist struggles to finish his work w...,Sine Olivia tl
45463,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",American World Pictures,Betrayal,en,0.903007,Action Drama Thriller When one of her hits goe...,American World Pictures en
45464,,"In a small town live two brothers, one a minis...",Yermoliev,Satan Triumphant,en,0.003503,"In a small town live two brothers, one a mini...",Yermoliev en
45465,,50 years after decriminalisation of homosexual...,,Queerama,en,0.163015,50 years after decriminalisation of homosexua...,en

In [31]:
df=df.drop(['overview','production_companies','original_language','genres'],axis=1)

In [32]:
df

,title,popularity,tag1,tag2
0,Toy Story,21.946943,"Animation Comedy Family Led by Woody, Andy's t...",Pixar Animation Studios en
1,Jumanji,17.015539,Adventure Fantasy Family When siblings Judy an...,TriStar Pictures Teitler Film Interscope Commu...
2,Grumpier Old Men,11.7129,Romance Comedy A family wedding reignites the ...,Warner Bros. Lancaster Gate en
3,Waiting to Exhale,3.859495,"Comedy Drama Romance Cheated on, mistreated an...",Twentieth Century Fox Film Corporation en
4,Father of the Bride Part II,8.387519,Comedy Just when George Banks has recovered fr...,Sandollar Productions Touchstone Pictures en
...,...,...,...,...
45461,Subdue,0.072051,Drama Family Rising and falling between a man ...,fa
45462,Century of Birthing,0.178241,Drama An artist struggles to finish his work w...,Sine Olivia tl
45463,Betrayal,0.903007,Action Drama Thriller When one of her hits goe...,American World Pictures en
45464,Satan Triumphant,0.003503,"In a small town live two brothers, one a mini...",Yermoliev en
45465,Queerama,0.163015,50 years after decriminalisation of homosexua...,en

In [50]:
df=df.reset_index(drop=True)

In [51]:
df

,title,popularity,tag1,tag2
0,Toy Story,21.946943,animation comedy family led woody andys toy li...,pixar animation studio en
1,Jumanji,17.015539,adventure fantasy family sibling judy peter di...,tristar picture teitler film interscope commun...
2,Grumpier Old Men,11.7129,romance comedy family wedding reignites ancien...,warner bros lancaster gate en
3,Waiting to Exhale,3.859495,comedy drama romance cheated mistreated steppe...,twentieth century fox film corporation en
4,Father of the Bride Part II,8.387519,comedy george bank recovered daughter wedding ...,sandollar production touchstone picture en
...,...,...,...,...
45442,Subdue,0.072051,drama family rising falling man woman,fa
45443,Century of Birthing,0.178241,drama artist struggle finish work storyline cu...,sine olivia tl
45444,Betrayal,0.903007,action drama thriller one hit go wrong profess...,american world picture en
45445,Satan Triumphant,0.003503,small town live two brother one minister one h...,yermoliev en
45446,Queerama,0.163015,year decriminalisation homosexuality uk direct...,en

In [54]:
df['title'].duplicated().sum()

3170

In [56]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

In [57]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [35]:
import nltk
import re

In [36]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [37]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [38]:
def preprocess(text):
    # lowercase
    text=str(text).lower()
    # remove puncuation
    text=re.sub(r'[^a-zA-Z\s]','',text)
    # Tokenization
    words=word_tokenize(text)
    # Remove Stopwords
    words=[word for word in words if word not in stop_words]
    # Lemmatization
    words=[lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [39]:
df['tag1'][0]

"Animation Comedy Family Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [40]:
preprocess(df['tag1'][0])

'animation comedy family led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference'

In [41]:
df["tag1"]=df['tag1'].apply(preprocess)
df['tag2']=df['tag2'].apply(preprocess)

In [42]:
df

,title,popularity,tag1,tag2
0,Toy Story,21.946943,animation comedy family led woody andys toy li...,pixar animation studio en
1,Jumanji,17.015539,adventure fantasy family sibling judy peter di...,tristar picture teitler film interscope commun...
2,Grumpier Old Men,11.7129,romance comedy family wedding reignites ancien...,warner bros lancaster gate en
3,Waiting to Exhale,3.859495,comedy drama romance cheated mistreated steppe...,twentieth century fox film corporation en
4,Father of the Bride Part II,8.387519,comedy george bank recovered daughter wedding ...,sandollar production touchstone picture en
...,...,...,...,...
45461,Subdue,0.072051,drama family rising falling man woman,fa
45462,Century of Birthing,0.178241,drama artist struggle finish work storyline cu...,sine olivia tl
45463,Betrayal,0.903007,action drama thriller one hit go wrong profess...,american world picture en
45464,Satan Triumphant,0.003503,small town live two brother one minister one h...,yermoliev en
45465,Queerama,0.163015,year decriminalisation homosexuality uk direct...,en

In [43]:
df.isnull().sum()

title         0
popularity    0
tag1          0
tag2          0
dtype: int64

In [44]:
# Vector Embedding

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [46]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2))

In [47]:
tfidf_metrix_tag1=tfidf.fit_transform(df['tag1'])
tfidf_metrix_tag2=tfidf.fit_transform(df['tag2'])

In [48]:
tfidf_metrix_tag1.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [102]:
def recommend(title,n=10):       #n=10 means 10 movies suggestions
    if title not in indices:
        return ["Movie not found"]
    idx=indices[title]
    score1=cosine_similarity(tfidf_metrix_tag1[idx],tfidf_metrix_tag1).flatten()
    score2=cosine_similarity(tfidf_metrix_tag2[idx],tfidf_metrix_tag2).flatten()
    score=(score1+score2)/2
    similarity_idx=score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similarity_idx]

In [117]:
recommend('Inception')

18247    The Dark Knight Rises
42152       Kong: Skull Island
22869             Interstellar
12478          The Dark Knight
11351             The Prestige
28278             Crimson Peak
21061             Man of Steel
11008        Lady in the Water
16837             Sucker Punch
15803                 The Town
Name: title, dtype: object

In [112]:
(tfidf_metrix_tag1 + tfidf_metrix_tag2)/2

<45447x50000 sparse matrix of type '<class 'numpy.float64'>'
	with 1964666 stored elements in Compressed Sparse Row format>

In [116]:

import pickle
tfidf_metrix=(tfidf_metrix_tag1+tfidf_metrix_tag2)/2
pickle.dump(tfidf_metrix,open("tfidf_metrix.pkl",'wb'))
pickle.dump(indices,open("indices.pkl",'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))